// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0MmeUseo8TNBvBwWttsQwm-M0K1V0bFg',
    appId: '1:426360469274:web:a144a55474529e9869dea3',
    messagingSenderId: '426360469274',
    projectId: 'pplconnect-9a466',
    authDomain: 'pplconnect-9a466.firebaseapp.com',
    storageBucket: 'pplconnect-9a466.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJCMQPW7oFCpxMayGNebTzLJ6pbk70_6Y',
    appId: '1:426360469274:android:aa0b5b587879a2b769dea3',
    messagingSenderId: '426360469274',
    projectId: 'pplconnect-9a466',
    storageBucket: 'pplconnect-9a466.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2pF8ffY4LS8P2ch-oBxl_pVZALho3MEM',
    appId: '1:426360469274:ios:8e2d141ded68263d69dea3',
    messagingSenderId: '426360469274',
    projectId: 'pplconnect-9a466',
    storageBucket: 'pplconnect-9a466.appspot.com',
    iosBundleId: 'com.example.pplconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2pF8ffY4LS8P2ch-oBxl_pVZALho3MEM',
    appId: '1:426360469274:ios:8e2d141ded68263d69dea3',
    messagingSenderId: '426360469274',
    projectId: 'pplconnect-9a466',
    storageBucket: 'pplconnect-9a466.appspot.com',
    iosBundleId: 'com.example.pplconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0MmeUseo8TNBvBwWttsQwm-M0K1V0bFg',
    appId: '1:426360469274:web:a0ea60d66906e05a69dea3',
    messagingSenderId: '426360469274',
    projectId: 'pplconnect-9a466',
    authDomain: 'pplconnect-9a466.firebaseapp.com',
    storageBucket: 'pplconnect-9a466.appspot.com',
  );
}